name: Go

on:
  push:
    branches: [ main ]

jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build and delpoy uService INDEX
        run: |
          cd cli/aws/index
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main main.go
          zip deployment.zip main
          aws lambda update-function-code --function-name=IndexModel --zip-file=fileb://deployment.zip

      - name: Build and delpoy uService GET
        run: |
          cd cli/aws/get
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main main.go
          zip deployment.zip main
          aws lambda update-function-code --function-name=GetModel --zip-file=fileb://deployment.zip
